[theme]
primaryColor = "#2ea043"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f6f8fa"
textColor = "#24292e"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 200


[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
fastReruns = true

[client]
showErrorDetails = true
toolbarMode = "auto"

[logger]
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[deprecation]
showfileUploaderEncoding = false
showImageFormat = false
showPyplotGlobalUse = false